# Generated by Django 2.2.7 on 2019-12-02 08:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='API key')),
                ('name', models.CharField(default='My e-scooter', max_length=32, verbose_name='Name')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Scooter'), (1, 'Bike'), (2, 'Scooter (motorcycle)')], default=1, verbose_name='Vehicle ')),
                ('serial_number', models.SlugField(verbose_name='Serial Number')),
                ('battery', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Battery status')),
                ('image', models.ImageField(blank=True, upload_to='uploads/', verbose_name='Picture')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Start time')),
                ('end', models.DateTimeField(verbose_name='End time')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nanogrid.Vehicle')),
            ],
        ),
    ]
